name: Notify chanel in Discord And Deploy
run-name: Notify and Deploy in Railway
on: 
  push:
    branches:
    - main
jobs:
  Notify-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The {{ EVENT_PAYLOAD.repository.full_name }} has been pushed with {{ EVENT_PAYLOAD.sender.login }}.'

  Deploy:
    needs: Notify-Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: 'psicologia-mb'
          detach: false
